### ISSUE TITLE
Valid requests fail if dropdown boxes are left at default selection

### ISSUE THREAD

**Issue by dmmcinty** [synapsestudios/lively#116]
## Description

When using the dropdown element to have users select input from a pre-defined set of selections, if the dropdown is left at the default when the request is submitted, it will fail with a false error. The error is usually something along the lines of "This field is missing", depending on the endpoint used.

**Comment by paulstatezny** [comment]
:boom: So, turns out this is not a bug. The problem is when you create an `enum` field and explicitly provide an invalid `defaultValue`. Like this:

```JSON
{
    name         : 'foo',
    defaultValue : null,
    type         : 'enum',
    enumValues   : ['bar', 'baz']
}
```

**Comment by nearengine** [comment]
:o: If no `defaultValue` is specified, we should be able to recover without causing errors IMO. We at least need to make what is being submitted correspond  to what is displayed in the form element - if I'm not mistaken, in your example, Lively would be displaying `'bar'` in the dropdown menu, but would actually submit `null`. I think that *should* be considered a bug. We could also display a blank option in the select box so the user realizes that nothing will be submitted for that value.

**Comment by nearengine** [comment]
:boom: :confounded: Sorry, I was conflating this with a different issue

**Comment by paulstatezny** [comment]
@nearengine I think you're partially correct in your original assessment.

If no `defaultValue` is specified, it passively chooses the first `enumValues` element, in order to match the UI's default state. (Dropdown automatically selects the first `option`, that's an HTML behavior.) I think that is desirable.

However, allowing an invalid `defaultValue` isn't desirable. I opened a new bug for this: #122.
