### ISSUE TITLE
github config incorrect

### ISSUE THREAD

**Issue by aecarr2** [synapsestudios/lively#117]
## Description

Comparing lively and the github docs there was a mismatch between config files on #114.

1. **Starring**
    * List repositories being starred with star creation timestamps

1. **Trees**
    * Get a Tree Recursively

1.  **Members**
    * Get organization membership
    * Add or update organization membership
    * Remove organization membership
    * List your organization memberships
    * Get your organization membership
    * Edit your organization membership

1. **Webhooks - Entirety**

    * Scopes & Restrictions
    * List hooks
    * Get single hook
    * Create a hook
    * Edit a hook
    * Ping a hook
    * Delete a hook
    * Receiving Webhooks

1. **Review Comments**
    * Reply to a comment - Not on git, should this be on lively still?

1. **Downloads - entirety**
    * List downloads for a repository
    * Get a single download
    * Delete a download

1. **Legacy Search - entirety**
    * Search issues
    * Search repositories
    * Search users
    * Email search

**Comment by agerbens** [comment]
1. The functionality to make this work is not on lively at the moment. Filed #118 for this, but please ignore it for this issue. 
2. Get a Tree Recursively is the same endpoint as Get a Tree, just with "recursive=1" in the querystring. There's an input for that on the Get a Tree endpoint. 
3. The top 3 bullets have the same problem as 1 and can be added at a later time. I'll add the bottom 3 bullets.
4. Organizations/Webhooks has the same problem as 1 and can be added at a later time.
5. This endpoint was created because github's api allows for alternative input, and lively doesn't have a great way to handle that atm. https://developer.github.com/v3/pulls/comments/#alternative-input
6. The Downloads API has been deprecated 2 years ago and will be removed at some point, so it was just never added to the lively configs. Please ignore it.
7. Same as 6. It was deprecated before the lively configs were created, so it was just never added. Please ignore.

Thanks for being so thorough! I'll make the change in 3 and then throw it back into testing.

**Comment by agerbens** [comment]
:pray:

**Comment by aecarr2** [comment]
:+1:
